[smallMolecule]

inchiKey = "inchikey"
smiles = "canonical_smiles"

[protein]

ecnumber = "ecnumber"
organism = "organism"
organismTaxId = "organism_tax_id"
sequence = "sequence"

[complex]
participants = "participants"

[conditions]

ph = { "@value" = "ph" }
temperature = { "@value" = "temperature", "@unit" = "temperature_unit" }

[parameter]

lowerBound = "lower"
upperBound = "upper"
stdDeviation = "stderr"

[measurement]

"@id" = "id"
"@name" = "name"

[speciesData]

speciesData = { "@species" = "species_id", "@value" = "initial", "@unit" = "data_unit", "@type" = "data_type" }

[variables]

variable = { "@id" = "id", "@name" = "name", "@symbol" = "symbol" }
