# Generated by PySCeS 1.2.3 (2025-07-30 10:33)
 
# Keywords
Description: ABTS measurement
Modelname: ABTS measurement
Output_In_Conc: True
Species_In_Conc: True
 
# GlobalUnitDefinitions
UnitSubstance: mole, 1.0, 0, 1
UnitVolume: litre, 1.0, 0, 1
UnitTime: second, 1.0, 0, 1
UnitLength: metre, 1.0, 0, 1
UnitArea: metre, 1.0, 0, 2
 
# Compartments
Compartment: vessel0, 1.0, 3 
 
# Reactions
reaction0@vessel0:
    abts > abts_radical
    k_cat*slac*abts/(K_M+abts)

reaction1@vessel0:
    slac > slac_inactive
    k_ie*slac
 
# Fixed species
 
# Variable species
slac@vessel0 = 0.079037949
slac_inactive@vessel0 = 0.0
abts@vessel0 = 4.37288121844535
buffer@vessel0 = 100.0
abts_radical@vessel0 = 0.0
 
# Parameters
k_cat = 1.85
K_M = 20.0
k_ie = 0.001
 

